#!/bin/bash

function err() {
  echo "ERROR: $1"
  exit 1
}

function info() {
  echo "INFO: $1"
}

function check() {
  if [ -z $1 ]; then
    err "did not find $2"
  fi
  info "$2 == $1"
}

function remotehas() {
  rv=$(ssh $1 "which $2")
  if [ -z $rv ]; then
    err "Did not find $2 on $1"
  fi
}
