#!/bin/bash

source common

uname=$(uname)
jar=$(ls augustmc-*.jar)
check $jar "jar"

OPTS=""
if [ $uname == "Darwin" ]; then
  target="dmg"
elif [ $uname == "Linux" ]; then
  OPTS="-Bcategory=Game" 
  target="deb"
else
  err "unsupported build environment: $uname"
fi

version=${jar#"augustmc-"}
version=${version%".jar"}

info "version: $version"
rm -Rf packages
javapackager -deploy -native $target -outdir packages -outfile augustmc \
    -srcfiles $jar -appclass com.simontuffs.onejar.Boot \
    -name "AugustMC" -title "August MC $version" -v -BappVersion=$version $OPTS
